"""Accounts, exclusive reservations, test rooms and private durable attachments."""
import re
import secrets
from pathlib import PurePath
from store import AppError, field

ACTIVE = ('reserved', 'confirmed', 'in_progress', 'submitted')
FILE_LIMIT = 2 * 1024 * 1024

class HiringMixin:
    def migrate_hiring(self, db):
        additions = {
            'sessions': [('account_id', 'INTEGER')],
            'jobs': [('owner_id', 'INTEGER'), ('active_reservation_id', 'INTEGER'),
                     ('test_brief', "TEXT NOT NULL DEFAULT 'Descrivi come affronteresti il ruolo e presenta un esempio pratico del tuo lavoro.'")],
        }
        for table, columns in additions.items():
            if self.database_url:
                existing = {r['column_name'] for r in db.execute('SELECT column_name FROM information_schema.columns WHERE table_schema=current_schema() AND table_name=?', (table,))}
            else:
                existing = {r['name'] for r in db.execute(f'PRAGMA table_info({table})')}
            for name, kind in columns:
                if name not in existing:
                    db.execute(f'ALTER TABLE {table} ADD COLUMN {name} {kind}')
        db.executescript('''
            CREATE TABLE IF NOT EXISTS accounts (
                id INTEGER PRIMARY KEY, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL,
                role TEXT NOT NULL, name TEXT NOT NULL,
                candidate_id INTEGER NOT NULL REFERENCES candidates(id), created_at REAL NOT NULL
            );
            CREATE TABLE IF NOT EXISTS reservations (
                id INTEGER PRIMARY KEY, job_id INTEGER NOT NULL REFERENCES jobs(id),
                candidate_id INTEGER NOT NULL REFERENCES candidates(id), status TEXT NOT NULL,
                reserved_until REAL NOT NULL, created_at REAL NOT NULL,
                motivation TEXT NOT NULL DEFAULT '', availability TEXT NOT NULL DEFAULT '',
                started_at REAL, submitted_at REAL, response TEXT NOT NULL DEFAULT '',
                review_note TEXT NOT NULL DEFAULT ''
            );
            CREATE INDEX IF NOT EXISTS reservations_job ON reservations(job_id);
            CREATE INDEX IF NOT EXISTS reservations_candidate ON reservations(candidate_id);
        ''')
        blob = 'BYTEA' if self.database_url else 'BLOB'
        db.execute(f'''CREATE TABLE IF NOT EXISTS attachments (
            id INTEGER PRIMARY KEY,
            job_id INTEGER NOT NULL REFERENCES jobs(id), reservation_id INTEGER REFERENCES reservations(id),
            name TEXT NOT NULL, content {blob} NOT NULL, created_at REAL NOT NULL
        )''' if not self.database_url else '''CREATE TABLE IF NOT EXISTS attachments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_id BIGINT NOT NULL REFERENCES jobs(id), reservation_id BIGINT REFERENCES reservations(id),
            name TEXT NOT NULL, content BYTEA NOT NULL, created_at DOUBLE PRECISION NOT NULL)''')
        db.executescript('''CREATE TABLE IF NOT EXISTS auth_attempts (
            key TEXT PRIMARY KEY, failures INTEGER NOT NULL, reset_at REAL NOT NULL
        );''')

    def account(self, account_id):
        if not account_id:
            return None
        with self.connect() as db:
            row = db.execute('SELECT id,email,role,name,candidate_id FROM accounts WHERE id=?', (account_id,)).fetchone()
            return dict(row) if row else None

    def register(self, data):
        from werkzeug.security import generate_password_hash
        email = field(data, 'email', 254).lower()
        name = field(data, 'name', 100)
        password = field(data, 'password', 256)
        role = data.get('role')
        if role not in ('candidate', 'employer') or not re.fullmatch(r'[^\s@]+@[^\s@]+\.[^\s@]+', email):
            raise AppError('Ruolo o email non valido.')
        if len(password) < 12:
            raise AppError('Usa una password di almeno 12 caratteri.')
        password_hash = generate_password_hash(password, method='scrypt')
        with self.connect() as db:
            if not self.database_url:
                db.execute('BEGIN IMMEDIATE')
            if self.database_url:
                # Avoid concurrent registrations of the same email without leaking SQL errors.
                db.execute('SELECT pg_advisory_xact_lock(hashtext(?))', (email,))
            if db.execute('SELECT 1 FROM accounts WHERE email=?', (email,)).fetchone():
                raise AppError('Email già registrata. Accedi al tuo account.', 409)
            cid = db.execute('INSERT INTO candidates (name,email) VALUES (?,?)', (name,email)).lastrowid
            aid = db.execute('INSERT INTO accounts (email,password_hash,role,name,candidate_id,created_at) VALUES (?,?,?,?,?,?)',
                             (email,password_hash,role,name,cid,self.clock())).lastrowid
        return self.account(aid)

    def authenticate(self, data, key):
        from werkzeug.security import check_password_hash, generate_password_hash
        email = field(data, 'email', 254).lower()
        password = field(data, 'password', 256)
        now = self.clock()
        with self.connect() as db:
            attempt = db.execute('SELECT * FROM auth_attempts WHERE key=?', (key,)).fetchone()
            if attempt and attempt['reset_at'] > now and attempt['failures'] >= 8:
                raise AppError('Troppi tentativi. Riprova tra 15 minuti.', 429)
            row = db.execute('SELECT * FROM accounts WHERE email=?', (email,)).fetchone()
        # Run a password hash even for unknown addresses.
        hashed = row['password_hash'] if row else generate_password_hash('unused-placeholder-password',method='scrypt')
        good = check_password_hash(hashed,password) and row and row['role'] == data.get('role')
        with self.connect() as db:
            if good:
                db.execute('DELETE FROM auth_attempts WHERE key=?', (key,))
            else:
                failures = attempt['failures'] + 1 if attempt and attempt['reset_at'] > now else 1
                db.execute('INSERT INTO auth_attempts (key,failures,reset_at) VALUES (?,?,?) ON CONFLICT(key) DO UPDATE SET failures=excluded.failures,reset_at=excluded.reset_at', (key,failures,now+900))
        if not good:
            raise AppError('Email, password o tipo di accesso non corretto.',401)
        return self.account(row['id'])

    def switch_account(self, old_token, account=None):
        with self.connect() as db:
            db.execute('DELETE FROM sessions WHERE token=?', (old_token,))
            cid = account['candidate_id'] if account else db.execute('INSERT INTO candidates DEFAULT VALUES').lastrowid
            session = dict(token=secrets.token_urlsafe(32),candidate_id=cid,csrf=secrets.token_urlsafe(32),expires_at=self.clock()+30*86400,account_id=account['id'] if account else None)
            db.execute('INSERT INTO sessions (token,candidate_id,csrf,expires_at,account_id) VALUES (:token,:candidate_id,:csrf,:expires_at,:account_id)',session)
        return session

    def lock_job(self, db, job_id):
        if not self.database_url and not db.in_transaction:
            db.execute('BEGIN IMMEDIATE')
        row = db.execute('SELECT * FROM jobs WHERE id=?'+(' FOR UPDATE' if self.database_url else ''),(job_id,)).fetchone()
        if not row:
            raise AppError('Offerta non trovata.',404)
        return dict(row)

    def release_expired(self, db, job=None):
        rows = [job] if job else db.execute('SELECT * FROM jobs WHERE active_reservation_id IS NOT NULL ORDER BY id').fetchall()
        for row in rows:
            locked = self.lock_job(db,row['id']) if job is None else row
            if locked['active_reservation_id']:
                r = db.execute('SELECT * FROM reservations WHERE id=?',(locked['active_reservation_id'],)).fetchone()
                if r and r['status'] in ('reserved','confirmed') and r['reserved_until'] <= self.clock():
                    db.execute("UPDATE reservations SET status='expired' WHERE id=?",(r['id'],))
                    db.execute('UPDATE jobs SET active_reservation_id=NULL,paused_until=0 WHERE id=?',(locked['id'],))
                    locked['active_reservation_id'] = None
            if job is not None:
                return locked

    def feed(self, candidate_id):
        with self.connect() as db:
            self.release_expired(db)
            rows = db.execute('''SELECT * FROM jobs j WHERE closed=0 AND active_reservation_id IS NULL AND paused_until<=?
                AND NOT EXISTS (SELECT 1 FROM passes p WHERE p.job_id=j.id AND p.candidate_id=?) ORDER BY id''',(self.clock(),candidate_id)).fetchall()
            return [self.job_json(r) for r in rows]

    def reserve(self, candidate_id, job_id):
        with self.connect() as db:
            job = self.release_expired(db,self.lock_job(db,job_id))
            if job['closed'] or job['active_reservation_id'] or job['paused_until'] > self.clock():
                raise AppError('Offerta già prenotata o non disponibile.',409)
            profile = db.execute('SELECT * FROM candidates WHERE id=?',(candidate_id,)).fetchone()
            if not profile['name'] or not profile['email']:
                raise AppError('Completa il profilo prima dello swipe.')
            until = self.clock()+self.pause_seconds
            rid = db.execute("INSERT INTO reservations (job_id,candidate_id,status,reserved_until,created_at) VALUES (?,?,'reserved',?,?)",(job_id,candidate_id,until,self.clock())).lastrowid
            db.execute('UPDATE jobs SET active_reservation_id=?,paused_until=0 WHERE id=?',(rid,job_id))
            db.execute('DELETE FROM passes WHERE job_id=? AND candidate_id=?',(job_id,candidate_id))
        return dict(id=rid,reserved_until=until,message='Offerta prenotata. Conferma e avvia il test entro la scadenza.')

    def reservation_action(self, candidate_id, rid, action, data):
        with self.connect() as db:
            r = db.execute('SELECT * FROM reservations WHERE id=? AND candidate_id=?',(rid,candidate_id)).fetchone()
            if not r:
                raise AppError('Candidatura non trovata.',404)
            job = self.release_expired(db,self.lock_job(db,r['job_id']))
            r = db.execute('SELECT * FROM reservations WHERE id=?',(rid,)).fetchone()
            if job['active_reservation_id'] != rid or r['status'] not in ACTIVE:
                raise AppError('Prenotazione scaduta o candidatura conclusa.',409)
            if action == 'confirm' and r['status'] == 'reserved':
                motivation = field(data,'motivation',2000)
                availability = field(data,'availability',500)
                if len(motivation) < 30 or data.get('commitment') is not True:
                    raise AppError('Scrivi almeno 30 caratteri e conferma di voler svolgere il test.')
                db.execute("UPDATE reservations SET status='confirmed',motivation=?,availability=? WHERE id=?",(motivation,availability,rid))
            elif action == 'start' and r['status'] == 'confirmed':
                db.execute("UPDATE reservations SET status='in_progress',started_at=? WHERE id=?",(self.clock(),rid))
            elif action == 'submit' and r['status'] == 'in_progress':
                response = field(data,'response',20000,False)
                files = db.execute('SELECT 1 FROM attachments WHERE reservation_id=?',(rid,)).fetchone()
                if len(response) < 30 and not files:
                    raise AppError('Inserisci una risposta di almeno 30 caratteri oppure allega il tuo lavoro.')
                db.execute("UPDATE reservations SET status='submitted',response=?,submitted_at=? WHERE id=?",(response,self.clock(),rid))
            else:
                raise AppError('Passaggio non consentito.',409)
        return {'message':'Candidatura aggiornata.'}

    def reservation_json(self, db, r):
        result = dict(r)
        result['attachments'] = [dict(x) for x in db.execute('SELECT id,name FROM attachments WHERE reservation_id=? ORDER BY id',(r['id'],))]
        result['test_files'] = [dict(x) for x in db.execute('SELECT id,name FROM attachments WHERE job_id=? AND reservation_id IS NULL ORDER BY id',(r['job_id'],))]
        return result

    def candidate_reservations(self, candidate_id):
        with self.connect() as db:
            self.release_expired(db)
            return [self.reservation_json(db,r) for r in db.execute('''SELECT r.*,j.title,j.company,j.test_brief FROM reservations r JOIN jobs j ON j.id=r.job_id WHERE r.candidate_id=? ORDER BY r.id DESC''',(candidate_id,))]

    def employer_jobs(self, owner_id=None, legacy=False):
        with self.connect() as db:
            self.release_expired(db)
            rows = db.execute('SELECT * FROM jobs WHERE '+('owner_id IS NULL' if legacy else 'owner_id=?')+' ORDER BY id DESC',None if legacy else (owner_id,))
            jobs = []
            for row in rows:
                job = self.job_json(row)
                job['workflow_status'] = 'hired' if job['closed']==2 else 'closed' if job['closed'] else 'active'
                job['candidates'] = [self.reservation_json(db,r) for r in db.execute('''SELECT r.*,c.name,c.email,c.skills FROM reservations r JOIN candidates c ON c.id=r.candidate_id WHERE r.job_id=? ORDER BY r.id DESC''',(job['id'],))]
                current = next((r for r in job['candidates'] if r['id']==job['active_reservation_id']),None)
                if current:job['workflow_status']=current['status']
                job['test_files'] = [dict(x) for x in db.execute('SELECT id,name FROM attachments WHERE job_id=? AND reservation_id IS NULL',(job['id'],))]
                jobs.append(job)
            return jobs

    def authorize_job(self, job, owner_id, legacy=False):
        if not ((legacy and job['owner_id'] is None) or (owner_id and job['owner_id']==owner_id)):
            raise AppError('Offerta non accessibile.',404)

    def employer_state(self, job_id, action, owner_id=None, legacy=False, note=''):
        with self.connect() as db:
            job = self.lock_job(db,job_id)
            self.authorize_job(job,owner_id,legacy)
            if job['closed']==2:
                raise AppError('Candidato selezionato: questa offerta è conclusa definitivamente.',409)
            rid = job['active_reservation_id']
            r = db.execute('SELECT * FROM reservations WHERE id=?',(rid,)).fetchone() if rid else None
            if action=='select':
                if not r or r['status']!='submitted':
                    raise AppError('Puoi selezionare un candidato solo dopo la consegna del test.',409)
                db.execute("UPDATE reservations SET status='hired',review_note=? WHERE id=?",(note,rid))
                db.execute('UPDATE jobs SET closed=2 WHERE id=?',(job_id,))
            elif action in ('reopen','close'):
                if r and r['status'] in ACTIVE:
                    db.execute('UPDATE reservations SET status=?,review_note=? WHERE id=?',('failed' if action=='reopen' else 'cancelled',note,rid))
                db.execute('UPDATE jobs SET active_reservation_id=NULL,paused_until=0,closed=? WHERE id=?',(int(action=='close'),job_id))
            else:raise AppError('Azione non valida.')
        return {'message':'Offerta e candidatura aggiornate.'}

    def add_attachment(self, job_id, rid, name, content, candidate_id=None, owner_id=None, legacy=False):
        name = PurePath(name.replace('\\','/')).name[:120]
        if not name or not content or len(content)>FILE_LIMIT:
            raise AppError('Ogni file deve contenere dati e non superare 2 MB.')
        with self.connect() as db:
            job = self.lock_job(db,job_id)
            if rid is None:
                self.authorize_job(job,owner_id,legacy)
                if job['active_reservation_id'] or job['closed']:
                    raise AppError('Gli allegati del test si possono aggiungere solo prima della prenotazione.',409)
                total = db.execute('SELECT COUNT(*) AS n FROM attachments WHERE job_id=? AND reservation_id IS NULL',(job_id,)).fetchone()['n']
            else:
                r = db.execute('SELECT * FROM reservations WHERE id=? AND job_id=?',(rid,job_id)).fetchone()
                if not r or r['candidate_id']!=candidate_id or r['status']!='in_progress' or job['active_reservation_id']!=rid:
                    raise AppError('Test non accessibile per la consegna.',409)
                total = db.execute('SELECT COUNT(*) AS n FROM attachments WHERE reservation_id=?',(rid,)).fetchone()['n']
            if total>=5:raise AppError('Puoi allegare al massimo 5 file.')
            fid = db.execute('INSERT INTO attachments (job_id,reservation_id,name,content,created_at) VALUES (?,?,?,?,?)',(job_id,rid,name,content,self.clock())).lastrowid
        return {'id':fid,'name':name}

    def attachment(self, fid, candidate_id=None, owner_id=None, legacy=False):
        with self.connect() as db:
            f = db.execute('SELECT * FROM attachments WHERE id=?',(fid,)).fetchone()
            if not f:raise AppError('File non trovato.',404)
            job = db.execute('SELECT * FROM jobs WHERE id=?',(f['job_id'],)).fetchone()
            employer_access = (legacy and job['owner_id'] is None) or (owner_id and job['owner_id']==owner_id)
            if not employer_access:
                if not candidate_id:raise AppError('File non accessibile.',404)
                if f['reservation_id']:
                    r = db.execute('SELECT * FROM reservations WHERE id=?',(f['reservation_id'],)).fetchone()
                    allowed = r and r['candidate_id']==candidate_id
                else:
                    allowed = db.execute('SELECT 1 FROM reservations WHERE job_id=? AND candidate_id=?',(f['job_id'],candidate_id)).fetchone()
                if not allowed:raise AppError('File non accessibile.',404)
            return dict(f)
