"""Small adapter for the parameterized statements shared with the SQLite store."""
import re


class Result:
    def __init__(self, cursor, inserted_id=None):
        self.cursor = cursor
        self.lastrowid = inserted_id

    @property
    def rowcount(self):
        return self.cursor.rowcount

    def fetchone(self):
        return self.cursor.fetchone()

    def fetchall(self):
        return self.cursor.fetchall()

    def __iter__(self):
        return iter(self.cursor)


class Connection:
    def __init__(self, connection):
        self.connection = connection

    @staticmethod
    def statement(sql, parameters=None):
        if isinstance(parameters, dict):
            sql = re.sub(r"(?<!:):([a-zA-Z_]\w*)", r"%(\1)s", sql)
        else:
            sql = sql.replace("?", "%s")
        if "INSERT OR IGNORE INTO passes" in sql:
            sql = sql.replace("INSERT OR IGNORE INTO", "INSERT INTO") + " ON CONFLICT DO NOTHING"
        return sql

    def execute(self, sql, parameters=None):
        sql = self.statement(sql, parameters)
        returns_id = bool(re.match(r"\s*INSERT INTO (?:candidates|jobs|accounts|reservations|attachments)\b", sql))
        if returns_id:
            sql += " RETURNING id"
        cursor = self.connection.execute(sql, parameters)
        return Result(cursor, cursor.fetchone()["id"] if returns_id else None)

    def executemany(self, sql, parameters):
        with self.connection.cursor() as cursor:
            cursor.executemany(self.statement(sql), parameters)

    def executescript(self, sql):
        sql = sql.replace("PRAGMA journal_mode=WAL;", "")
        sql = sql.replace("id INTEGER PRIMARY KEY", "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
        sql = re.sub(r"\bINTEGER\b", "BIGINT", sql)
        sql = re.sub(r"\bREAL\b", "DOUBLE PRECISION", sql)
        for statement in sql.split(";"):
            if statement.strip():
                self.connection.execute(statement)
